### ISSUE TITLE
about:memory

### ISSUE THREAD

**Issue by Popog** [NiklasGollenstede/stylish#2]
about:memory needs more dark, something like?

```
@-moz-document
    url(about:memory)
{
    div.opsRow
    {
        background-color: rgba(0,0,0, .5) !important;
    }
    div.section
    {
        background-color: rgba(0,0,0, .5) !important;
    }
}
```

**Comment by NiklasGollenstede** [comment]
"more dark"? For me (Release x86 45, Beta x64 46) the Background of the entire page is pitch black.

Which (exact) version of Firefox are you using?

**Comment by Popog** [comment]
Release x64 45.0.1

The background is dark, but the `div`s are white text on white.

See attached images for [before](https://cloud.githubusercontent.com/assets/761307/14406084/37c90124-fe6c-11e5-80a9-355752d8e945.png) and [after](https://cloud.githubusercontent.com/assets/761307/14406085/3a07c146-fe6c-11e5-81a2-b06e98a9a558.png).

**Comment by NiklasGollenstede** [comment]
Bouth classes you suggested to restyle have ""background: -moz-Field;" (in my setup of firefox, and I think that's the standard).
The reason that it looks different for you propably is, that you are (maybe implicitly due to yout OS?) are using a theme that resolves: -moz-Field to something other than white, which causes the white background (when inverted).

What I don't understaind is how you can have any visual contrast between the text and the div background whitout my style

**Comment by NiklasGollenstede** [comment]
I tried Firefox on Windows 10 with and without the Developer Theme

**Comment by Popog** [comment]
Ah, I see. It seems to be a [Gnome dark theme bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1158076). Guess I'll just shove it in manually myself as a work around.

**Comment by NiklasGollenstede** [comment]
I think it would be best if you do that.
I always try to keep the number of rules in my inversion styles as low as possible, manual fixes for one thing have the tenancy of braking something else / later.

("shove it in manually": You should do your fix in a different file, otherwise it will be overwritten the next time I update the style on userstyles.org)
