### ISSUE TITLE
Dialogs Dark - Media details

### ISSUE THREAD

**Issue by friendlyanon** [NiklasGollenstede/stylish#9]
The preview gets inverted and I don't know why the invert rule doesn't apply to it as well even tho `img` is defined.

![example](http://i.imgur.com/anaJ5a1.png)

**Comment by NiklasGollenstede** [comment]
It admittedly took me a moment to find this, bit the fix is rather simple:
The UI in the popups is XUL, so I declared the styles namespace to be XUL. Bbut the `img` is actually an HTML element and thus can't be addressed from an XUL namespace.
To fix this, the HTML namespace has to be declared too, and the selector must be changed to `*|img`, which means `img`in any namespace. ( `html|img` works too.)
